;; 外部elのインストールが必要な設定
;; ========================================
;; sticky
;; ========================================
;; ----大文字入力をshiftを離したあとでもできるようにする----
;; sitickyを読み込む
;; (require 'sticky)
;; 日本語キーボードで、shitfキーをshiftキーとして使う(shift以外をshiftにも置き\\
換えられるが置き換えない)
;; (use-sticky-key ";" sticky-alist:ja)

;; ----バッファ切替、ファイルを開くときの指定方法を拡張----
;; ------------------------------
;; (iswitch-mode t)
;; ------------------------------
;; ------------------------------
;; コマンドがidoに置き換わる
;; (ido-mode t)
;; ;; バッファ名 ファイル名入力がすべてidoに代わる
;; (ido-everywhere t)
;; -------------------------------

;; ========================================
;; anything
;; ========================================
;; ---- anything.el ----
(require 'anything-startup)
(require 'anything-config)
(add-to-list 'anything-sources 'anything-c-source-emacs-commands)
(defun my-anything ()
  "Anything command for you.
It is automatically generated by `anything-migrate-sources'."
  (interactive)
  (anything-other-buffer
    '(anything-c-source-buffers+ anything-c-source-recentf anything-c-source-fi\
les-in-current-dir+)
    "*my-anything*"))
(define-key global-map (kbd "C-x b") 'my-anything)

;; ========================================
;; elisp install
;; ========================================
;; ----emacsから自動でlispをインストールできるようにする----
;; install-elispを読み込む
(require 'install-elisp)
;; install-elispがdlするlispの保存先を指定する
(setq install-elisp-repository-directory "~/.emacs.d/site-lisp/auto-install")

;; ---- 上位版の設定 ----
(require 'auto-install)
(setq auto-install-directory "~/.emacs.d/site-lisp/auto-install/")
(auto-install-update-emacswiki-package-name t)
(auto-install-compatibility-setup)

;; ;; ---- さらに上位版 ----
;; ;; 参考URL: http://d.hatena.ne.jp/rubikitch/20101209
;; ;; (save-window-excursion (shell-command (format "emacs-test -l %s %s &" buf\
fer-file-name buffer-file-name)))
;; (add-to-list 'load-path "~/.emacs.d/el-get/el-get/")
;; (require 'el-get)
;; (load "2010-12-09-095707.el-get-ext.el")
;; ;; 初期化ファイルのワイルドカードを指定する
;; (setq el-get-init-files-pattern "~/emacs/init.d/[0-9]*.el")
;; (setq el-get-sources (el-get:packages))
;; (el-get)


;; ========================================
;; 補完機能
;; ========================================
;; auto-completeを読み込む
(require 'auto-complete)
(global-auto-complete-mode t)


;; ;; 略語から定型文の挿入
;; (require 'yasnippet-config)
;; ;; 推奨設定を関数にまとめている??
;; (yas/setup "~/.emacs.d/plugins/yasnippet-0.6.1c")

;; ----------------------------------------
;; popwin  http://d.hatena.ne.jp/m2ym/searchdiary?word=*[Emacs]
;; ----------------------------------------
;; default setting
(require 'popwin)
(setq display-buffer-function 'popwin:display-buffer)

;; settiong for popup *anything* buffer
(setq anything-samewindow nil)
(push '("*anything*" :height 20) popwin:special-display-config)

;; for dired buffer
(push '(dired-mode :position top) popwin:special-display-config)

;; (require 'dired-x)

;; ----------------------------------------
;; one-key  http://d.hatena.ne.jp/tomoya/20090415/1239809615
;; ----------------------------------------
(require 'one-key-default)              ;one-key.elも読み込む
(require 'one-key-config)
(one-key-default-setup-keys)

;; ----------------------------------------
;; tramp  リモートファイルを編集する
;; ----------------------------------------
;; 使えない??
(require 'tramp)

